import { createFileRoute } from "@tanstack/react-router";
import { PhoneShell } from "@/components/PhoneShell";
import { AppHeader } from "@/components/AppHeader";

export const Route = createFileRoute("/_authenticated/terms")({
  component: TermsPage,
  head: () => ({ meta: [{ title: "Terms & Conditions — Nurture" }] }),
});

function TermsPage() {
  return (
    <PhoneShell>
      <AppHeader title="Terms & Conditions" back />
      <div className="px-5 pb-8 space-y-4">
        <div className="text-xs text-muted-foreground">Last updated: July 8, 2026</div>
        <p className="text-sm leading-relaxed">
          Please read these Terms & Conditions carefully before using the Nurture app. By accessing or using the app, you agree to be bound by these terms.
        </p>

        <Section title="1. Acceptance of Terms">
          By creating an account or using Nurture, you agree to these Terms & Conditions and our Privacy Policy. If you do not agree, please do not use the app.
        </Section>
        <Section title="2. Use of the App">
          Nurture is a pregnancy tracking tool designed to support your pregnancy journey. The app is for informational and organizational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for medical concerns.
        </Section>
        <Section title="3. Account & Security">
          You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately of any unauthorized use.
        </Section>
        <Section title="4. User Conduct">
          You agree not to misuse the app, interfere with its operation, attempt to gain unauthorized access, or use it for any unlawful purpose. We may suspend or terminate accounts that violate these terms.
        </Section>
        <Section title="5. Intellectual Property">
          All content, branding, and software in Nurture are owned by or licensed to us. You may not copy, modify, distribute, or reverse-engineer any part of the app without our prior written permission.
        </Section>
        <Section title="6. Disclaimers">
          Nurture is provided "as is" without warranties of any kind. We do not guarantee that the app will be error-free, uninterrupted, or suitable for your specific needs. Health-related insights generated by the app are informational only.
        </Section>
        <Section title="7. Limitation of Liability">
          To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app.
        </Section>
        <Section title="8. Changes to These Terms">
          We may update these Terms & Conditions from time to time. Continued use of the app after changes constitutes acceptance of the revised terms.
        </Section>
        <Section title="9. Governing Law">
          These terms are governed by the laws applicable in your jurisdiction, without regard to conflict of law principles.
        </Section>
        <Section title="10. Contact">
          Questions about these Terms & Conditions? Reach us from Help & Support inside the app.
        </Section>
      </div>
    </PhoneShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="font-semibold text-sm">{title}</h2>
      <p className="mt-1 text-sm text-muted-foreground leading-relaxed">{children}</p>
    </div>
  );
}
